### ISSUE TITLE
Issue with multiple "dropdown fields (other)" in matrix field

### ISSUE THREAD

**Issue by Spoowy** [supercool/Tools#14]
When you have two or more dropdown boxes in one matrix field, of the type of Dropdown (other), an issue occurs when clicking on the dropdowns.

If you click on a dropdown that is not the first in the field, it opens the textfield for the first dropdown.

Watch this video: https://sendvid.com/6jk5rrr1
Thanks

**Comment by Nav33d** [comment]
@Spoowy I have now fixed this issue: https://github.com/supercool/Tools/releases/tag/1.7.1
