### ISSUE TITLE
Missing js and css

### ISSUE THREAD

**Issue by migswd** [supercool/Tools#2]
I installed the news version but I still have thoses 404 on plugin resources
![screen shot 2015-09-13 at 23 34 41](https://cloud.githubusercontent.com/assets/3531623/9839138/516fd2b0-5a70-11e5-8c95-319d835edfff.jpg)

**Comment by joshangell** [comment]
Try uninstalling and reinstalling it again?

**Comment by joshangell** [comment]
You won't lose any data held in fields, you'll just need to redo their settings later on.

**Comment by migswd** [comment]
OK great works infe now. Thx !

**Comment by joshangell** [comment]
Great!
